on: [push, pull_request]
name: test
jobs:
  test:
    name: test ${{ matrix.toolchain }} ${{ matrix.profile.name }} ${{ matrix.features }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.profile.flag }} --features=${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.40.0
          - stable
          - beta
          - nightly
        features:
          -
          - serde
          - std
        profile:
          - {name: debug}
          - {name: release, flag: --release}
